# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 840dcb9cc58ede5446fe927a817af66e5ebe81dd860d06cb8b72cd72c5e6f6e5f7523c8b5255b821deaf39daf3e5387dbe16d2d06d298a13c7c8faf5d19312d8

test:
  secret_key_base: a02ce5f2d9932f71f3c53a39e2014e79d6a3bcd4ce17e4debe4fba362a01ba8faafb4ce2b3f78db4150d4bd56433cb67235a6f8e991c8005027d2dba95d59c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
